### ISSUE TITLE
Something probably changed -- here's what I see in my logs

### ISSUE THREAD

**Issue by tumtumsback** [thevoltagesource/LennoxiComfort#34]
2021-11-07 10:48:44 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform myicomfort
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 298, in state_attributes
if self.hvac_action:
File "/config/custom_components/myicomfort/climate.py", line 226, in hvac_action
return HVAC_ACTIONS[self._api.state]
IndexError: list index out of range
2021-11-07 10:48:44 ERROR (MainThread) [homeassistant.components.climate] Error while setting up myicomfort platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 607, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 715, in add_to_platform_finish
self.async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 486, in async_write_ha_state
self._async_write_ha_state()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 521, in _async_write_ha_state
attr.update(self.state_attributes or {})
File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 298, in state_attributes
if self.hvac_action:
File "/config/custom_components/myicomfort/climate.py", line 226, in hvac_action
return HVAC_ACTIONS[self._api.state]
IndexError: list index out of range

**Comment by tumtumsback** [comment]
It's working now -- what sure what changed?

**Comment by thevoltagesource** [comment]
I thought I had responded to this... Based on those logs it would appear to be a similar issue to #25.  Hopefully things are still working for you.  If not check out the the issue #25 and the recent beta release [v3.1-beta.1](https://github.com/thevoltagesource/LennoxiComfort/releases/tag/v3.1-beta.1) with Aux Heat support.  Since you have reported that the issue self corrected, at least for now, I will close out this issue.
