### ISSUE TITLE
MyiComfort will not load

### ISSUE THREAD

**Issue by restauffer** [thevoltagesource/LennoxiComfort#52]
I  am getting an error when Home Assistant triesto load  the myicomfort integration. I have V3.4.1 of the  myicomfort integration. I noted the problem the day after I upgraded from HA Core 11.3 to 12.1. I also updated Zwave that day. I have since rolled back both updates but the problem persists. Here is the relevant code from the home-assistant.log

2024-12-09 15:17:54.289 ERROR (SyncWorker_17) [myicomfort.api] Thermostat cloud service not responding.
2024-12-09 15:17:54.293 ERROR (MainThread) [homeassistant] Error doing job: Task exception was never retrieved (None)
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 1046, in _async_update_entity_states
    await entity.async_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 962, in async_update_ha_state
    self._async_write_ha_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1132, in _async_write_ha_state
    self.__async_calculate_state()
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1069, in __async_calculate_state
    state = self._stringify_state(available)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 1013, in _stringify_state
    if (state := self.state) is None:
                 ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 469, in state
    hvac_mode = self.hvac_mode
                ^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/climate/__init__.py", line 324, in __getattribute__
    return super().__getattribute__(__name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/myicomfort/climate.py", line 254, in hvac_mode
    return HVAC_MODES[self._api.op_mode]
           ~~~~~~~~~~^^^^^^^^^^^^^^^^^^^
TypeError: list indices must be integers or slices, not NoneType

Any ideas how to resolve the issue?

Thanks

Ricke

**Comment by CCupler** [comment]
+1 here. iComfort integration isn't working since I updated HA to 2024.12.1 on Sunday. 

Logger: custom_components.myicomfort.climate
Source: custom_components/myicomfort/climate.py:158
integration: Lennox iComfort WiFI (documentation, issues)
First occurred: 12:16:10 AM (1 occurrences)
Last logged: 12:16:10 AM

Failed to connect to thermostat cloud API.

also 
Logger: myicomfort.api
Source: custom_components/myicomfort/climate.py:152
integration: Lennox iComfort WiFI ([documentation](https://github.com/thevoltagesource/LennoxiComfort), [issues](https://github.com/thevoltagesource/LennoxiComfort/issues))
First occurred: 12:16:10 AM (1 occurrences)
Last logged: 12:16:10 AM 

No, I had not changed my credentials.

**Comment by thevoltagesource** [comment]
The error makes it sound like Lennox's cloud service was down when your instance tried to load the API.  I just loaded the API directly I am able to connect to my account and pull data. I will dig in to this more today and see what else might be wrong.  Please let me know if it is still not working this morning.

**Comment by restauffer** [comment]
> The error makes it sound like Lennox's cloud service was down when your instance tried to load the API. I just loaded the API directly I am able to connect to my account and pull data. I will dig in to this more today and see what else might be wrong. Please let me know if it is still not working this morning.

I think you are right. Mine is now working. It must have been a coincidence that the cloud service failed right after I updated HA but it certainly explains why rolling HA back did not fix it. Thanks for checking on it.

**Comment by bateschris** [comment]
For what it's worth, I had this occurring as well.  Even using the android app for the tstat was failing with a "You changed your password, login with new password" error appearing (I hadn't changed anything). Logging into their web site via browser was working fine however, using the same credentials that failed in the app. 

Today it magically started working again, so I'm going with "It's not you, it's them"!

**Comment by stilldisturbing** [comment]
I just upgraded my system and it is working fine.  Think that might have been you issue (connection problem) as I have see this before where if during init it can't read the current status it generates an error.

**Comment by CCupler** [comment]
> The error makes it sound like Lennox's cloud service was down when your instance tried to load the API. I just loaded the API directly I am able to connect to my account and pull data. I will dig in to this more today and see what else might be wrong. Please let me know if it is still not working this morning.

Looks like something went wonky with my MyConfortSync account. I couldn't log in to it.  ((shrugs)) 
Ended up needing to de-register the thermostat, delete the account, and set it up again. 
Works now. 

It was just an odd coincidence that this happened at about the same time I did the HA upgrade. I literally had thermostat data right up until that reboot.

**Comment by Atf1120** [comment]
Newbie here. I cannot get the script to save. Error when attempting. Sorry in advance
